name: Deploy to Rental Server

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run tests (if any)
      run: npm test --if-present
      
    - name: Deploy to rental server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          # プロジェクトディレクトリに移動
          cd ${{ secrets.PROJECT_PATH }}
          
          # Gitから最新のコードを取得
          git pull origin main
          
          # 依存関係をインストール
          npm ci --production
          
          # アプリケーションを再起動
          pm2 restart english-grammar-app || pm2 start server.js --name english-grammar-app
          
          # ログを確認
          pm2 logs english-grammar-app --lines 10 