name: Deploy to Rental Server

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run tests (if any)
      run: npm test --if-present
      
    - name: Deploy to rental server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          # プロジェクトディレクトリに移動
          cd ${{ secrets.PROJECT_PATH }}
          
          # 現在のプロセスを停止
          pm2 stop english-grammar-app || true
          
          # Gitから最新のコードを取得
          git fetch origin
          git reset --hard origin/main
          
          # 依存関係をインストール
          npm ci --production
          
          # 環境変数ファイルが存在しない場合は作成
          if [ ! -f .env ]; then
            echo "Creating .env file..."
            cp env.example .env || echo "No env.example found"
          fi
          
          # アプリケーションを起動
          pm2 start server.js --name english-grammar-app --update-env
          
          # プロセスが正常に起動したか確認
          sleep 5
          pm2 status
          
          # ログを確認
          pm2 logs english-grammar-app --lines 10
          
          # メモリ使用量を確認
          pm2 monit --no-daemon &
          sleep 10
          pkill -f "pm2 monit" 