name: Deploy to Rental Server

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Deploy to rental server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          set -e
          
          echo "=== Deployment Start ==="
          echo "Current user: $(whoami)"
          echo "Current directory: $(pwd)"
          
          # Validate required secrets
          if [ -z "${{ secrets.PROJECT_PATH }}" ]; then
            echo "ERROR: PROJECT_PATH secret is not set"
            exit 1
          fi
          
          PROJECT_PATH="${{ secrets.PROJECT_PATH }}"
          echo "PROJECT_PATH: '$PROJECT_PATH'"
          
          # Create and navigate to project directory
          mkdir -p "$PROJECT_PATH"
          cd "$PROJECT_PATH"
          echo "Working directory: $(pwd)"
          
          # Backup existing files if any
          if [ -f "index.html" ]; then
            BACKUP_DIR="backup_$(date +%Y%m%d_%H%M%S)"
            mkdir -p "$BACKUP_DIR"
            cp -r * "$BACKUP_DIR/" 2>/dev/null || true
            echo "Backup created: $BACKUP_DIR"
          fi
          
          # Copy static files
          echo "Copying static files..."
          
          # Copy HTML files
          cp -r *.html . 2>/dev/null || echo "No HTML files found"
          
          # Copy CSS files
          cp -r *.css . 2>/dev/null || echo "No CSS files found"
          
          # Copy JavaScript files (excluding server files)
          cp script.js . 2>/dev/null || echo "No script.js found"
          cp navigation.js . 2>/dev/null || echo "No navigation.js found"
          cp static-data.js . 2>/dev/null || echo "No static-data.js found"
          
          # Copy data files
          cp grammar.json . 2>/dev/null || echo "No grammar.json found"
          cp examples.js . 2>/dev/null || echo "No examples.js found"
          
          # Copy directories
          for dir in parts-of-speech sentence-patterns phrases clauses sentence-types tenses modals subjunctive comparison mood components; do
            if [ -d "$dir" ]; then
              cp -r "$dir" . 2>/dev/null || echo "Failed to copy $dir"
            else
              echo "Directory $dir not found"
            fi
          done
          
          # Remove server files
          rm -f server.js app.js package.json package-lock.json ecosystem.config.js env.example
          rm -rf node_modules .github .git
          rm -f .gitignore .gitattributes README.md *.ps1
          rm -rf scripts
          
          echo "Deployment completed successfully"
          echo "Files in directory:"
          ls -la
          
          echo "=== Deployment End ==="